language: node_js
node_js:
  - stable

script:
  - make lint
  - make test

addons:
  code_climate:
    repo_token: 684f0d565b7bd2608af0453457dd19903b818c16ded1e386d9c5a21c72291be5

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info